# Build stage
FROM node:20-alpine AS builder
RUN apk update
RUN apk add git

RUN npm install -g pm2

WORKDIR /app
RUN git clone https://github.com/lillabajnai/aidb.git
WORKDIR /app/aidb
RUN git checkout devops

WORKDIR /app/aidb/server
RUN npm install
RUN npm run build

# Install rsyslog
RUN apk add --no-cache rsyslog
# Create rsyslog config
COPY rsyslog.conf /etc/rsyslog.conf

RUN mkdir -p /var/log/pm2

# Configure PM2 to use syslog
ENV PM2_SYSLOG=true
EXPOSE 5000 10050

# Start rsyslog and PM2
CMD ["sh", "-c", "rsyslogd && pm2-runtime start build/index.js --output /var/log/pm2/out.log --error /var/log/pm2/error.log"]